// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import EventSubscriptionController from "./event_subscription_controller"
application.register("event-subscription", EventSubscriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
